### ISSUE TITLE
Test LIDARDrive

### ISSUE THREAD

**Issue by poojaswami16** [team178/2017RobotCode#16]

**Comment by gisellegk** [comment]
- get the lidar from the "bag" robot (this was the one from FHS)
- see if you can consistently get distance values using the LIDARDistance command
if yes:
- run LIDAR drive and see if it stops after a certain distance (in front of a wall)
if no: 
- try an ultrasonic sensor?

**Comment by poojaswami16** [comment]
it's dead.
