### ISSUE TITLE
ShiftSpeed command causing issues

### ISSUE THREAD

**Issue by gisellegk** [team178/2017RobotCode#2]
1. there is a null pointer exception when the isFinished() method is called.
2. Calling the ShiftSpeed command disables JoystickDrive.

possible suggestions:
- create two commands, one that's like JoystickDriveLow / JoystickDriveHi
- separate subsystems for the shifter and the rest of the drive train
- make JoystickDrive listen for the trigger, rather than having ShiftSpeed be a separate command

**Comment by gisellegk** [comment]
If you check out commit 5055f05 , there are two separate problems here (that might end up being fixed at the same time?). One is that we're using "whilePressed" in OI, which is ending the command without calling end(). The other is that the line in isFinished() throws a null pointer exception.

I think we might be able to avoid both of these issues altogether by following one of those suggestions, but it's also important to understand why the code is behaving this way (and why we have to change stuff)

**Comment by poojaswami16** [comment]
Greg and I worked together to try to fix the code. Do you want to take a look at it? When we go FULL STEAM AHEAD AHAHAH GET IT BC STEAMWORKS, it randomly switches gears between hi and low, and we're not sure if that's an us problem or a mechanical problem, possibly both?

**Comment by gisellegk** [comment]
@poojpooj what file(s) should I look at specifically?
