### ISSUE TITLE
Vertical / Horizontal camera dimensions

### ISSUE THREAD

**Issue by gisellegk** [team178/2017RobotCode#25]
```
if (isVertical) { // vertical
  IMG_WIDTH = 800;
  IMG_HEIGHT = 600;
} else { // horizontal
  IMG_WIDTH = 600;
  IMG_HEIGHT = 800;
}
```

I'm pretty sure now that these are switched. When the camera is in "vertical" position (ie. the shooter) it has a "wide" aspect ratio (like a TV screen). When the camera is in "horizontal" position (ie. the gear gobbler) it has a "narrow" aspect ratio (like a phone camera). 

The code above is copy pasted from the VisionStreamer constructor, and does not reflect the above statements.

This may or may not be contributing to the issues @poojpooj and I were having today.

**Comment by poojaswami16** [comment]
We also don't have to worry about this because both cameras are going to be vertical.
