### ISSUE TITLE
Fix and Test AutoDrivefoward/DriveDistance

### ISSUE THREAD

**Issue by gisellegk** [team178/2017RobotCode#4]

**Comment by poojaswami16** [comment]
@gisellegk I've been working with Greg and Kathleen to try to fix this problem using PIDdrive, but we can't find much information on how to use it. Do you have any suggestions? Should we put it on ChiefDelphi?

**Comment by gisellegk** [comment]
@poojpooj Ask Chief Delphi probably. PID is the right way to go but it should be possible to write this command without it? The team hasn't really used PID successfully in the past

**Comment by gisellegk** [comment]
But if we can make it work we should
