### ISSUE TITLE
Test autonomous commands

### ISSUE THREAD

**Issue by Elizabeth-Cho** [team178/2017RobotCode#7]
Seeing as how we have some autonomous commands written/started, we might as well start testing to make sure they generally do what we want. 

- [x] AutoGearSequence
- [x] AutoLightRobot 
- [x] AutoHam (Does both gears and shoot in autonomous)

**Comment by FishOfPitt116** [comment]
Didn't we just do this?? All we have to do is shoot fuel right??

**Comment by Elizabeth-Cho** [comment]
@FishOfPitt116 The issue is still open because we haven't tested all of the autonomous options yet. We know for sure that AutoGearSequence works, but not necessarily for AutoLight or AutoDouble/AutoHam.
